# Generated by Django 3.2.4 on 2021-06-18 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField()),
                ('comment', models.TextField()),
                ('id_meeting_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.meetingroom')),
            ],
            options={
                'unique_together': {('reservation_date', 'id_meeting_room')},
            },
        ),
    ]
