# Generated by Django 3.2.4 on 2021-06-19 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_date',
            new_name='date',
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('date', 'id_meeting_room')},
        ),
    ]
